### ISSUE TITLE
Automatically play controller?

### ISSUE THREAD

**Issue by musjj** [nixon-voxell/bevy_motiongfx#41]
Right now the following system is necessary, if you want your animation to actually play:

```rust
fn play_controller(time: Res<Time>, mut controller_query: Query<&mut SequenceController>) {
    for mut controller in &mut controller_query {
        controller.target_time += time.delta_seconds();
    }
}
```

I think the more user-friendly approach is to have the controller *automatically* play and let the user pause/seek it only if they want to.

**Comment by nixon-voxell** [comment]
yeah that would be possible, but I want to give users more control over how the animation would be played, maybe we can create a custom system or plugin for it and users can choose to opt-in or not.

Or do we leave this control completely to the users themselves? Cuz I was thinking like, it only needs to be setup once haha.

**Comment by musjj** [comment]
I think automatically playing is a way better default. But there should also be a way to manually control it, if the user wants to.

Maybe something like:
```rust
#[derive(Default)]
enum ControllerMode {
    #[default]
    Auto,
    Manual,
}

commands.spawn(SequencePlayerBundle {
    sequence,
    sequence_controller: SequenceController {
        mode: ControllerMode::Manual,
        ..default()
    },
    ..default()
});
```

Or maybe with a helper method:
```rust
commands.spawn(
    (SequencePlayerBundle {
        sequence,
        ..default()
    })
    .with_manual(),
);
```

Not sure what's the most ergonomic approach.

**Comment by musjj** [comment]
It looks like that you *can* actually make it automatically play:

```rust
commands.spawn(SequencePlayerBundle {
    sequence,
    sequence_player: SequencePlayer { time_scale: 1.0 },
    ..default()
});
```

Because of this system:

https://github.com/nixon-voxell/bevy_motiongfx/blob/c109d31da471598ea3168fc49613d4658a817a95/crates/motiongfx_core/src/sequence.rs#L238-L249

I'm kinda confused, when was this added? I guess this issue can be closed?

**Comment by nixon-voxell** [comment]
Oh this was the component to control the sequence haha, the `time_scale` default to 0.0 is actually because I did not do anything fancy and just `#[derive(Default)]` for the component hahaha.

**Comment by nixon-voxell** [comment]
If you think that solves the issue (which I agree) I guessed it can be.

**Comment by musjj** [comment]
Yeah, I'll close it for now.
